---
# 2.1 Time Synchronization
# 2.1.1 Ensure time synchronization is in use
# 2.1.1.1 Ensure chrony is configured

- name: 2.1.1.1 Ensure chrony is configured
  block:
    - name: Install chrony
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Ensure chrony is enabled and running
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes

    - name: Configure chrony
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: "{{ item.state }}"
      loop:
        - {regexp: "^server ", line: "server time.example.com iburst", state: "present"}
        - {regexp: "^allow ", line: "", state: "absent"}
        - {regexp: "^listen on", line: "", state: "absent"}
        - {regexp: "^local stratum", line: "", state: "absent"}
        - {regexp: "^manual", line: "", state: "absent"}
        - {regexp: "^mlockall", line: "", state: "absent"}
