---
# 1.3 Filesystem Integrity Checking
# 1.3.1 Ensure AIDE is installed
- name: 1.3.1 Ensure AIDE is installed
  ansible.builtin.package:
    name: aide
    state: present

# 1.3.2 Ensure filesystem integrity is regularly checked
- name: 1.3.2 Ensure filesystem integrity is regularly checked
  ansible.builtin.cron:
    name: "AIDE filesystem integrity check"
    minute: "0"
    hour: "5"
    user: root
    job: "/usr/bin/aide --config /etc/aide/aide.conf --check"
