---
# 1.4 Secure Boot Settings
# 1.4.1 Ensure permissions on bootloader config are configured
- name: 1.4.1 Ensure permissions on bootloader config are configured
  ansible.builtin.file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: '0400'

# 1.4.2 Ensure bootloader password is set
- name: 1.4.2 Ensure bootloader password is set
  block:
    - name: Check if bootloader password is set
      ansible.builtin.command:
        cmd: grep "^set superusers=" /boot/grub/grub.cfg
      register: bootloader_password
      check_mode: no
      changed_when: false

    - name: Set bootloader password
      ansible.builtin.command:
        cmd: grub-mkpasswd-pbkdf2 | tee /tmp/grubpassword
      when: bootloader_password.stdout == ""

    - name: Update bootloader configuration with password
      ansible.builtin.lineinfile:
        path: /etc/grub.d/40_custom
        insertafter: "exec tail"
        line: 'set superusers="root"'
      when: bootloader_password.stdout == ""

    - name: Update bootloader configuration with encrypted password
      ansible.builtin.lineinfile:
        path: /etc/grub.d/40_custom
        insertafter: "set superusers"
        line: "password_pbkdf2 root {{ lookup('file', '/tmp/grubpassword') }}"
      when: bootloader_password.stdout == ""

    - name: Update grub configuration
      ansible.builtin.command:
        cmd: update-grub
      when: bootloader_password.stdout == ""

# 1.4.3 Ensure authentication required for single user mode
# This task is distribution-specific and may require manual verification.

# 1.4.4 Ensure interactive boot is not enabled
- name: 1.4.4 Ensure interactive boot is not enabled
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_DISABLE_RECOVERY='
    line: 'GRUB_DISABLE_RECOVERY=true'
  notify: update grub