---
# 1.7 Warning Banners
# 1.7.1 Command Line Warning Banners
# 1.7.1.1 Ensure message of the day is configured properly
- name: 1.7.1.1 Ensure message of the day is configured properly
  ansible.builtin.lineinfile:
    path: /etc/motd
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  loop:
    - {regexp: "Authorized uses only", line: "Authorized uses only. All activity may be monitored and reported.", state: "present"}
    - {regexp: "^\\s*#", line: "", state: "absent"}
  notify: restart sshd

# 1.7.1.2 Ensure local login warning banner is configured properly
- name: 1.7.1.2 Ensure local login warning banner is configured properly
  ansible.builtin.lineinfile:
    path: /etc/issue
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  loop:
    - {regexp: "Authorized uses only", line: "Authorized uses only. All activity may be monitored and reported.", state: "present"}
    - {regexp: "^\\s*#", line: "", state: "absent"}

# 1.7.1.3 Ensure remote login warning banner is configured properly
- name: 1.7.1.3 Ensure remote login warning banner is configured properly
  ansible.builtin.lineinfile:
    path: /etc/issue.net
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  loop:
    - {regexp: "Authorized uses only", line: "Authorized uses only. All activity may be monitored and reported.", state: "present"}
    - {regexp: "^\\s*#", line: "", state: "absent"}

# 1.7.1.4 Ensure permissions on /etc/motd are configured
- name: 1.7.1.4 Ensure permissions on /etc/motd are configured
  ansible.builtin.file:
    path: /etc/motd
    owner: root
    group: root
    mode: '0644'

# 1.7.1.5 Ensure permissions on /etc/issue are configured
- name: 1.7.1.5 Ensure permissions on /etc/issue are configured
  ansible.builtin.file:
    path: /etc/issue
    owner: root
    group: root
    mode: '0644'

# 1.7.1.6 Ensure permissions on /etc/issue.net are configured
- name: 1.7.1.6 Ensure permissions on /etc/issue.net are configured
  ansible.builtin.file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
