---
# 1.8 Ensure updates, patches, and additional security software are installed
- name: 1.8 Ensure updates, patches, and additional security software are installed
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: safe

    - name: Install unattended-upgrades package
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present

    - name: Enable unattended-upgrades
      ansible.builtin.copy:
        src: /usr/share/unattended-upgrades/20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        mode: '0644'
